
KEY: "hungthinh"
MYSQL_HOST: "127.0.0.1"
MYSQL_PORT: "3307"
MYSQL_USER: "root"
MYSQL_PASSWORD: "thinh123"
MYSQL_DB: "StockData"
STOCK_EXCHANGE_PORT: "5010"
REDIS_PORT: "6868"
REDIS_HOST: "127.0.0.1"

