
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
    networks:
      - stock-exchange-apis-networks

  stock-echange:
    build: 
        context: ../stock-exchange-api
        dockerfile: Dockerfile
    container_name: stock-exchange
    restart: unless-stopped 
    environment:
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - ${STOCK_EXCHANGE_PORT}:5000
    # volumes:
    #     - ./data_file:/app/data
    networks:
      - stock-exchange-apis-networks

  redis:  
    image: redis:latest
    container_name: redis-container
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - stock-exchange-apis-networks

networks:
  stock-exchange-apis-networks:
    name:  stock-exchange-apis-networks
    driver: bridge
    external: true



# docker-compose --env-file config.yaml up --detach
# docker-compose stop stock-echange
# docker-compose build stock-echange
# docker-compose up -d stock-echange
# docker-compose --env-file .env --file ./docker-compose.yaml up --detach
# docker run -v ./Users/macos/Desktop:/Users/macos/Downloads/WORKSPACE/stock_project stock_project-stock-echange
#/Users/macos/Desktop