
version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    expose:
      - 3306

  web:
    image: python:3.9
    build: .
    ports:
      - "5010:5000"
    volumes:
      - .:/app  
    working_dir: /app
    command: /usr/local/bin/python3 app.py
    environment:
      - PIP=pip3





#docker-compose --file ./docker-compose.yaml up --detach
# docker exec -it mysql-container bash
# mysql -u root -p -P 3307


