FROM python:3.12


# Set the timezone to Asia/Ho_Chi_Minh
ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /cron_jobs

COPY requirements.txt .
RUN pip install --force-reinstall -r requirements.txt
COPY . .

CMD ["python3", "crawl_data.py"]
 
