FROM python:3.12

# Set the timezone to Asia/Ho_Chi_Minh
ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /stock-exchange-api

# Copy the requirements file from src to the working directory
COPY src/requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt
# Set PYTHONPATH to include src directory
ENV PYTHONPATH=/stock-exchange-api/src
ENV PYTHONPATH=/stock-exchange-api/src/config.py
ENV PYTHONPATH=/stock-exchange-api/src/config.yaml
ENV PYTHONPATH=/stock-exchange-api/
# Copy the rest of the project files
COPY . .

CMD ["python3", "cron_jobs/_init_.py"]
